services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=transactions
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password

    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: